## **Aprendizado Bayesiano**

Em **classificação**, o Aprendizado Bayesiano consiste em atualizar a probabilidade de uma classe $y$ após observar um dado $\mathbf{x}$.


### **Teorema de Bayes**

O núcleo desse processo é dado por:

$$
P(y \mid \mathbf{x}) = \dfrac{P(\mathbf{x} \mid y)\,P(y)}{P(\mathbf{x})}
$$

#### **Posterior**: $P(y \mid \mathbb{x})$

É a probabilidade da classe $y$ dado o dado observado $\mathbf{x}$:

$$
y \mid \mathbf{x} \sim P(y \mid \mathbf{x})
$$

Representa a crença atualizada sobre a classe.

#### **Likelihood (Verossimilhança)**: $P(\mathbf{x} \mid y)$

É a probabilidade de observar o dado $\mathbf{x}$ assumindo que a classe é $y$:

$$
\mathcal{L}(y) = P(\mathbf{x} \mid y)
$$

Mede o quão bem a classe $y$ explica o dado observado.

#### **Prior**: $P(y)$

É a probabilidade da classe antes de observar os dados:

$$
y \sim P(y)
$$

Representa a frequência ou crença inicial sobre cada classe.

#### **Evidence (Marginal Likelihood)**: $P(\mathbf{x})$

É um fator de normalização, dado por:

$$
P(\mathbf{x}) = \sum_{y} P(\mathbf{x} \mid y)\,P(y)
$$

Garante que $P(y \mid \mathbf{x})$ seja uma distribuição válida.

### **Forma utilizada na prática**

Como $P(\mathbf{x})$ é constante para todas as classes, utilizamos:

$$
P(y \mid \mathbf{x}) \propto P(\mathbf{x} \mid y)\,P(y)
$$

E a decisão é feita por:

$$
\hat{y} = \arg\max_y P(\mathbf{x} \mid y)\,P(y)
$$

Esse critério de decisão é conhecido como **Máximo a Posteriori (MAP)**.

### **Gaussian Naive Bayes**

#### **Fundamentação**

Neste modelo, assumimos que, para cada classe $c$ e para cada feature $x_i$, temos uma Gaussiana com **média** e **variância** próprias:

$$
x_i \mid y = c \sim \mathcal{N}(\mu_{c,i}, \sigma_{c, i}^{2})
$$

#### **Hipótese de Naive Bayes**

Assumimos que as features são independentes dado a classe:

$$
P(x_1, x_2, x_3, \dots, x_n \mid y) = \prod_{i=1}^{n}P(x_i \mid y)
$$

#### **Modelo Probabilístico**

Modelamos então probabilidade de uma amostra $x = (x_1, x_2, x_3, \dots, x_n)$ ser da classe $c$ como:

$$
P(y = c \mid x) \propto P(y = c)\prod_{i=1}^{n}P(x_i \mid y = c)
$$

onde:

*   $P(y = c)$ é o **prior**
*   $P(x_i \mid y = c)$ é o **likehood** e é dado pela distribuição normal:

$$
P(x_i \mid y = c) = \dfrac{1}{\sqrt{2\pi\sigma_{c,i}^{2}}} \exp \left(-\dfrac{(x_i - \mu_{c,i})}{2\sigma_{c,i}^{2}}\right)
$$

#### **Decisão da classe**

A predição é feita escolhendo a classe que maximiza a probabilidade posterior:

$$
\hat{y} = \arg\max_c P(y = c)\prod_{i=1}^{n}P(x_i \mid y = c)
$$

#### **Aplicação do logaritmo**

Como as probabilidades condicionais são tipicamente muito pequenas,

$$
P(x_i \mid y) \ll 1
$$

o produto dessas probabilidades pode rapidamente tender a zero:

$$
\prod_{i=1}^{n} P(x_i \mid y) \rightarrow 0
$$

causando problemas de underflow numérico.

Para contornar isso, aplicamos o logaritmo, que transforma produtos em somas e melhora a estabilidade numérica:

$$
\hat{y} = \arg\max_c \left[ \log P(y = c) + \sum_{i=1}^{n} \log P(x_i \mid y = c) \right].
$$

Como o logaritmo é uma função monotonicamente crescente, ele não altera o resultado do $\arg\max$.

### **Implementação do Naive Bayes para problema de Classificação**

Vamos utilizar **Gaussian Naive Bayes** para tarefa de **classificação**  no dataset [**Iris Flower Dataset**](https://scikit-learn.org/1.5/auto_examples/datasets/plot_iris_dataset.html).

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

In [76]:
iris = load_iris()

X = iris.data
y = iris.target

print("Shape de X:", X.shape)
print("Shape de y:", y.shape)

Shape de X: (150, 4)
Shape de y: (150,)

In [77]:
df = pd.DataFrame(X, columns=iris.feature_names)
df["species"] = y

df["species"] = df["species"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [78]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Treino:", X_train.shape)
print("Teste:", X_test.shape)

Treino: (120, 4)
Teste: (30, 4)

In [80]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

mean_train = X_train.mean().round(1)
var_train = X_train.var().round(1)

print("Dados de treino:")
print(f"Média: {mean_train}")
print(f"Variância: {var_train}")

mean_test = X_test.mean().round(1)
var_test = X_test.var().round(1)

print("\nDados de teste:")
print(f"Média: {mean_test}")
print(f"Variância: {var_test}")

Dados de treino:
Média: -0.0
Variância: 1.0

Dados de teste:
Média: 0.0
Variância: 0.9

#### **Implementação do Gaussian Neive Bayes**

In [81]:
classes = np.unique(y_train)

means = dict()
vars_ = dict()
priors = dict()

for c in classes:
    X_c = X_train[y_train == c]

    means[c] = X_c.mean(axis=0)
    vars_[c] = X_c.var(axis=0)
    priors[c] = len(X_c) / len(X_train)

In [82]:
def gaussian(x, mean, var):
    coeff = 1 / np.sqrt(2 * np.pi * var)
    exponent = np.exp(-(x - mean)**2 / (2 * var))
    return coeff * exponent

In [83]:
def predict(X):
    predictions = []

    for x in X:
        posteriors = []

        for c in classes:
            log_prior = np.log(priors[c])

            log_likelihood = 0
            for i in range(len(x)):
                prob = gaussian(x[i], means[c][i], vars_[c][i])
                log_likelihood += np.log(prob)

            posterior = log_prior + log_likelihood
            posteriors.append(posterior)

        predictions.append(np.argmax(posteriors))

    return np.array(predictions)

In [84]:
y_pred = predict(X_test)

accuracy = np.mean(y_pred == y_test)

print(f"Accuracy: {100 * accuracy.round(4)}%")

Accuracy: 96.67%